// Master slide registry
// hidden: true → not shown in sidebar; accessible via keyboard shortcut or button only

export const SECTIONS = [
  { num: '01', title: 'Opening & Context' },
  { num: '02', title: 'Background of the Study' },
  { num: '03', title: 'Objectives & Framework' },
  { num: '04', title: 'Review of Related Literature' },
  { num: '05', title: 'Methodology' },
  { num: '06', title: 'System Features & Architecture' },
  { num: '07', title: 'Evaluation Framework' },
  { num: '08', title: 'Significance & Summary' },
]

export const slides = [
  // ── SECTION 01 ──────────────────────────────────────────────
  {
    id: 's01', section: '01', sectionTitle: 'Opening & Context', type: 'title', title: 'SEN-GEN',
    notes: 'Good morning, distinguished panel members. I am Kenneth Rey Rallustian Tablang, a Master in Information Technology student at Universidad de Dagupan — School of Professional Studies, under the advisement of Prof. Rochelle Sotelo Lanto, MIT. I am presenting SEN-GEN: Student Enrollment with Generative Scheduling System for STI Alaminos. SEN-GEN is a proposed web-based system that I, as the sole researcher and developer, am proposing to design, develop, and implement to directly address the documented operational gaps in student enrollment and class scheduling at STI Alaminos. The proposed system will integrate a digital enrollment pipeline, an automated CSP-based scheduling engine, role-differentiated interfaces for six user roles, and an ISO 25010 evaluation framework. Over the next sixty minutes, I will walk you through the institutional problem, the literature that validates our approach, the methodology we plan to follow, the system we are proposing to build, and the evaluation framework that will measure its usability. Let us begin.',
  },
  {
    id: 's02', section: '01', sectionTitle: 'Opening & Context', type: 'content', title: 'Presentation Outline',
    notes: 'This presentation is structured into eight sections. Section One opens with context — my background as the researcher and the institutional setting of STI Alaminos. Section Two establishes the background of the study — eight specific operational gaps that motivated SEN-GEN, contextualized against Philippine HEI standards. Section Three presents our objectives and the IPO conceptual framework. Section Four reviews over thirty verified literature sources organized around our three specific objectives. Section Five covers the research design and methodology — specifically, Agile Feature-Driven Development. Section Six presents the proposed system architecture and all six functional modules. Section Seven describes the ISO 25010 evaluation framework we will use. And Section Eight covers the significance, regulatory alignment, and research summary. I will follow this structure throughout the presentation to ensure clarity and logical flow for the panel.',
  },
  {
    id: 's03', section: '01', sectionTitle: 'Opening & Context', type: 'content', title: 'About the Researcher',
    notes: 'To give the panel confidence in the authorship of this proposal, allow me to briefly describe my professional background. I have three years of experience in software development through freelance projects, two and a half years of teaching experience, and one year of overseas web content management work. This combined exposure to software engineering, education, and institutional operations directly informs the architectural decisions being made throughout SEN-GEN\'s design. My full-stack proficiency in React JS, ASP.NET Core Web API, SQL Server, and Entity Framework Core positions me to design, build, and deploy the proposed system from end to end — without outsourcing any component. This is important context for the panel because it means every design decision in SEN-GEN is intentional, grounded in technical competency, and defensible.',
  },
  {
    id: 's04', section: '01', sectionTitle: 'Opening & Context', type: 'content', title: 'Institutional Context',
    notes: 'SEN-GEN is purpose-built for STI Alaminos — a dynamic and growing private technical-vocational institution in Alaminos City, Pangasinan. The institution operates under the regulatory supervision of the Technical Education and Skills Development Authority, or TESDA, and simultaneously honors the policies of the Commission on Higher Education, given that most STI campuses are CHED-accredited. It serves Information Technology and allied programs. Two institutional realities are critical to understanding why SEN-GEN is needed. First, while STI Alaminos has its own institutional guidelines for distributing faculty teaching loads, the institution currently lacks any systematic mechanism to monitor whether those loads remain balanced once assigned — a monitoring gap that SEN-GEN\'s proposed scheduling engine is specifically designed to close. Second, the institution\'s existing apply.sti.edu registration portal has not been actively used by the Admission Officer due to several documented deficiencies: no terms and conditions disclosure, failure to enforce proper name capitalization, no input validation, and no document requirements checklist functionality. SEN-GEN directly addresses both of these gaps, among others.',
  },

  // ── SECTION 02 ──────────────────────────────────────────────
  {
    id: 's05', section: '02', sectionTitle: 'Background of the Study', type: 'divider', title: 'Background of the Study',
    notes: 'We now move to Section Two: the Background of the Study. This section establishes the specific institutional problems that motivate SEN-GEN. We document eight operational gaps at STI Alaminos, contextualize them against the digital enlistment standards of leading Philippine universities, and trace the consequences of inaction across all six stakeholder groups. Every claim in this section is grounded either in structured interviews conducted with STI Alaminos stakeholders, direct observation of their workflows, or peer-reviewed literature that quantifies the costs of manual enrollment and scheduling systems.',
  },
  {
    id: 's06', section: '02', sectionTitle: 'Background of the Study', type: 'content', title: 'The Core Problem',
    notes: 'At the heart of SEN-GEN is a single core problem: STI Alaminos has no integrated, digitally enabled system connecting the full enrollment pipeline. What the institution currently has instead is a cascade of eight compounding operational gaps. The first is the absence of a unified digital enrollment platform — all four enrollment steps are entirely manual. The second is the apply.sti.edu platform, which the Admission Officer does not actively use due to specific, documented deficiencies: no terms and conditions disclosure, forced lowercase name entry that corrupts student records, no input validation, no document upload, no confirmation email, and no enrollment term field. The third is the absence of a digital document submission checklist — missing pertinent papers are discovered late, creating incomplete records. The fourth is the absence of automated faculty load monitoring — STI Policy load guidelines are tracked manually, creating overloading risk. The fifth is the eighteen-to-twenty-two working day manual scheduling cycle. The sixth is the absence of an automated faculty loading report. The seventh is the absence of grid schedule views for faculty, classroom, and section. And the eighth is the compounding of data silos across disconnected files with no audit trail and no automated notifications. SEN-GEN is specifically proposed to close every one of these gaps.',
  },
  {
    id: 's07', section: '02', sectionTitle: 'Background of the Study', type: 'content', title: 'Philippine HEI Context',
    notes: 'To put these gaps in perspective, consider what leading Philippine universities have already achieved in digital enlistment. Ateneo de Manila University has operated the AISIS platform since 2005, enabling students to independently enlist in subjects during scheduled windows — entirely separate from tuition payment. The University of the Philippines Diliman uses the Computerized Registration System for mid-semester pre-enlistment with batch slot allocation. De La Salle University launched Animo.sys in 2013 with a cart-based subject selection interface. Far Eastern University uses Student Central NEO for real-time online enlistment with live fee computation. The University of Santo Tomas provides the myUSTe Portal for complete self-service enlistment and academic records management. Across all five institutions, subject enlistment is a structured, student-driven, digitally mediated process that precedes and is operationally distinct from payment. The literature notes that a dedicated student-facing enlistment platform is not a luxury but an institutional standard among Philippine HEI leaders — a standard that STI Alaminos has yet to achieve. SEN-GEN aims to bring STI Alaminos into alignment with that standard.',
  },
  {
    id: 's08', section: '02', sectionTitle: 'Background of the Study', type: 'content', title: 'Enrollment Process — 4 Steps (As-Is)',
    notes: 'Let me walk you through what a single enrollment period currently requires at STI Alaminos. Step One is document submission. A new student must physically appear at the admissions office to submit their Form 137, birth certificate, and good moral certificate, which the Admission Officer manually checks against a spreadsheet-based requirements list. There is no digital checklist, no system-generated tracking, and no notification when the review is complete. Step Two is registration. The student completes a paper-based Student Information Sheet. Although apply.sti.edu exists as an alternative, it is not used due to its documented deficiencies. Step Three is enlistment. The student must physically visit the registrar\'s office to determine which sections are available. The registrar manually verifies eligibility, checks slot counts on a spreadsheet, records the request on paper, and updates the count by hand — one student at a time, for every subject, across the entire enrollment period. When section capacities are exceeded or conflicts are discovered, registrar staff must contact affected students individually and coordinate corrections across multiple disconnected files. Step Four is tuition payment at the cashier. SEN-GEN aims to digitize Steps One through Three. Step Four is deliberately excluded — it involves financial transactions governed by separate institutional accounting controls. This boundary is a justified design decision, not an omission.',
  },
  {
    id: 's09', section: '02', sectionTitle: 'Background of the Study', type: 'content', title: 'Manual Scheduling Flow',
    notes: 'The manual scheduling process at STI Alaminos follows a predictable and labor-intensive pattern. A faculty coordinator opens a spreadsheet and begins checking room availability row by row — there is no automated conflict detection. Emails are sent to faculty members requesting their preferred time slots, and responses arrive at different times in different formats. A draft schedule is assembled and shared, then corrected when a room double-booking is discovered. Another revision follows when a faculty overload is identified. The cycle repeats until a workable — but rarely optimal — schedule is finally produced. Only after this labor-intensive process is completed can students attempt to enlist — and even then, they must physically visit the registrar to ask whether their preferred section still has available slots. Chen et al. in 2021 documented that institutions relying on manual scheduling consistently report elevated conflict rates, longer administrative resolution cycles, and lower faculty and student satisfaction. Bui et al. in 2022 established that this manual cycle takes eighteen to twenty-one working days, compared to two to four days with algorithmic tools — an eighty-six percent reduction. Veenstra and Vis in 2023 documented that manual schedule conflict density averages eight to twelve percent. Every one of these costs is preventable, and SEN-GEN\'s proposed CSP-based scheduling engine is designed to eliminate this entire cycle.',
  },
  {
    id: 's10', section: '02', sectionTitle: 'Background of the Study', type: 'content', title: 'Stakeholder Impact',
    notes: 'The operational gaps at STI Alaminos affect all six stakeholder roles in different but equally serious ways. The School Admin bears oversight responsibility for institutional performance but cannot access real-time data — only manually compiled, after-the-fact reports. The Academic Head must ensure class schedules are structured and faculty loads are distributed in accordance with STI\'s institutional guidelines — but without an integrated system, this monitoring requires manual cross-referencing of disconnected spreadsheets, making imbalances difficult to detect. The Registrar processes every enlistment request manually — one transaction at a time — while simultaneously handling walk-in inquiries and scheduling discrepancies. During peak enrollment periods, this volume exceeds the sustainable processing capacity of a small registrar\'s office. The Admission Officer manages document verification for every new enrollee without a digital mechanism, leading to duplicated effort and incomplete tracking. Faculty members are assigned teaching loads without any system-enforced mechanism to monitor whether those loads remain balanced in accordance with STI\'s institutional loading guidelines. And most critically, students — the primary beneficiaries of the enrollment process — must physically appear at the admissions and registrar\'s offices for each step. For a student who holds a part-time job, lives in a distant barangay, or lacks consistent transportation, this is a concrete and recurring barrier to equitable academic participation. SEN-GEN is proposed to address all six stakeholder groups with purpose-built, role-differentiated solutions.',
  },
  {
    id: 's11', section: '02', sectionTitle: 'Background of the Study', type: 'content', title: 'Consequences of Inaction',
    notes: 'Should SEN-GEN remain unimplemented, the consequences for STI Alaminos are both immediate and compounding. In the short term, the institution continues to absorb hidden operational costs: scheduling conflicts requiring hours of staff time to resolve, enrollment queues that degrade the student experience, incomplete document records from untracked submissions, and uneven faculty load distribution that goes undetected without a systematic monitoring mechanism. In the medium term, the institution risks falling behind STI institutional quality audit standards, which increasingly evaluate the transparency and efficiency of academic administrative systems as part of broader quality assurance frameworks. Students with geographic, economic, or time constraints continue to face structural inequity in access to enrollment services — a direct contradiction of the inclusive education principles in the institution\'s mandate. Faculty members without a load management tool remain vulnerable to academic overloading and schedule mismatches. In the long term, the absence of digital infrastructure means no historical data for evidence-based academic planning, no audit trail for STI compliance documentation, and a widening institutional credibility gap versus peer institutions. Leite in 2025 established that institutions investing in digital academic management tools demonstrate measurable positive shifts in administrative efficiency and stakeholder satisfaction. Every enrollment cycle that passes without SEN-GEN is a cycle of preventable, compounding institutional cost.',
  },

  // ── SECTION 03 ──────────────────────────────────────────────
  {
    id: 's12', section: '03', sectionTitle: 'Objectives & Framework', type: 'divider', title: 'Objectives & Framework',
    notes: 'We now move to Section Three: Objectives and Framework. This section presents the three specific research objectives that structure SEN-GEN and the IPO conceptual framework that illustrates how institutional inputs will be transformed through the system\'s development and operational processes into measurable outputs and institutional benefits. Both the objectives and the framework are grounded in the operational realities documented in Section Two, and they directly organize the literature review, methodology, and system features that follow.',
  },
  {
    id: 's13', section: '03', sectionTitle: 'Objectives & Framework', type: 'content', title: 'Statement of Objectives',
    notes: 'The main objective of this study is to design, develop, and implement SEN-GEN — a web-based Student Enrollment with Generative Scheduling System for STI Alaminos. This main objective is pursued through three specific objectives, each corresponding to a distinct research dimension. The first specific objective is descriptive: to identify and document the current procedures in student enrollment, class schedule management, and slot allocation at STI Alaminos. This objective has established the operational baseline — the eight gaps presented in Section Two — through structured interviews, non-participatory observation, and document analysis. The second specific objective is developmental: to determine and build the features of the proposed SEN-GEN system. This objective will be operationalized through Agile Feature-Driven Development, where each of the six system modules will be independently designed, built, and validated with stakeholder acceptance criteria before proceeding to the next. The third specific objective is evaluative: to assess the level of usability of the proposed system using the ISO 25010 software quality standard, to be administered to forty-five purposively sampled respondents targeting a weighted mean of at least 4.00 across six quality dimensions. All three objectives are addressed in the sections that follow.',
  },
  {
    id: 's14', section: '03', sectionTitle: 'Objectives & Framework', type: 'content', title: 'Conceptual Framework — IPO',
    notes: 'The IPO Model — Input, Process, Output — is the conceptual framework that illustrates how SEN-GEN will transform institutional data into institutional outcomes. On the Input side, we have two categories. Data inputs are the foundational institutional records: student profiles with program, year level, and curriculum data; subject records with unit loads and prerequisites; faculty profiles with teaching load capacities; room records with capacity and availability; the academic calendar; and system parameters including section capacity limits, allowable time slots, and institutional policy constraints. User inputs are the active participation of all six roles — students submitting enrollment documents and enlisting in subjects, the Registrar managing approvals and publishing schedules, the Admission Officer verifying document submissions, Faculty Members setting availability, the Academic Head monitoring load compliance, and the School Admin overseeing system configuration. In the Process phase, these inputs will flow through Feature-Driven Development during system construction, and through SEN-GEN\'s runtime logic during live operation — the CSP scheduling engine, the ETL pipeline, the enlistment workflow, the document checklist module, and the SIS registration module. The Output phase will produce optimized conflict-free schedules, faculty load summaries, enrollment records, room utilization reports, and audit logs — alongside five institutional benefits: reduced administrative workload, improved accuracy and fairness, enhanced student experience, optimized resource use, and data-driven decision-making. ISO 25010 evaluation will close the loop through a continuous feedback mechanism.',
  },
  {
    id: 's15', section: '03', sectionTitle: 'Objectives & Framework', type: 'content', title: 'Scope & Limitations',
    notes: 'The scope of SEN-GEN is precisely defined. The proposed system will cover: STI Alaminos campus exclusively; six user roles governed by role-based access control; ETL-based XLSX import for pre-enrollment authorization; the CSP Generative Scheduling Engine; a student portal with real-time slot availability and a maximum capacity of forty students per section; a digital enrollment requirements checklist for document submission tracking; faculty assignment with manual override and real-time conflict detection; a semester-aware dashboard with exportable reports; automated email notifications for six lifecycle events; grid views for faculty, classroom, and class sections; and ISO 25010 usability evaluation with forty-five respondents. There are four deliberate limitations. First, no multi-campus integration — SEN-GEN is purpose-built for STI Alaminos\'s specific operational context, and generalization will require contextual replication. Second, no financial or payment processing — tuition payment involves separate institutional financial controls. Third, no AI or ML predictive scheduling — the institution does not yet have sufficient historical scheduling data to train predictive models; CSP is the correct and well-validated foundational step, as documented by Diallo et al. in 2024. Fourth, findings are not generalizable without contextual replication in comparable institutions. Each limitation is deliberate, documented, and defensible.',
  },

  // ── SECTION 04 ──────────────────────────────────────────────
  {
    id: 's16', section: '04', sectionTitle: 'Review of Related Literature', type: 'divider', title: 'Review of Related Literature',
    notes: 'We now move to Section Four: the Review of Related Literature. This section reviews over thirty verified sources from international and Philippine academic publications spanning 2001 to 2025. The review is organized around our three specific objectives. For the first objective, we review literature documenting the operational costs of manual enrollment and scheduling. For the second objective, we review literature validating each of SEN-GEN\'s six proposed functional modules. For the third objective, we review literature providing ISO 25010 benchmark scores from comparable systems. Every SEN-GEN feature is validated by at least one peer-reviewed source. I will highlight the most critical sources and statistics that directly inform SEN-GEN\'s design and evaluation targets.',
  },
  {
    id: 's17', section: '04', sectionTitle: 'Review of Related Literature', type: 'content', title: 'Literature Overview',
    notes: 'The literature review is organized into three subsections, each aligned with one specific objective. For Objective One — documenting current procedures — the literature provides quantitative evidence of the costs of manual enrollment and scheduling that directly mirrors what we found at STI Alaminos through structured interviews and observation. For Objective Two — determining and building features — we reviewed sources validating the ETL pipeline through Mansoor et al. in 2022; the CSP scheduling engine through Diallo et al. in 2024 and Bui et al. in 2022; the RBAC architecture through Liu et al. in 2017 and Kim and Park in 2022; the semester-aware dashboard through Leite in 2025; and automated notifications through Martinez and Chen in 2023. For Objective Three — ISO 25010 usability evaluation — we reviewed benchmark scores from Bellio et al. in 2022, Gozali et al. in 2022, Diallo et al. in 2024, and Kim and Park in 2022. The benchmark range from these four comparable systems is 4.11 to 4.55. SEN-GEN will target at least 4.00 — a conservative threshold below the floor of all comparable systems. The synthesis of these sources establishes that SEN-GEN is technically feasible and institutionally positioned to achieve Very Good to Excellent usability ratings.',
  },
  {
    id: 's18', section: '04', sectionTitle: 'Review of Related Literature', type: 'content', title: 'Manual vs Algorithmic Scheduling',
    notes: 'The literature is remarkably consistent in quantifying the cost of manual scheduling. Chen et al. in 2021 surveyed university course timetabling across multiple institutions and documented that sixty-two percent of universities still use manual or semi-automated scheduling, with consistently elevated scheduling conflict rates, longer administrative resolution cycles, and lower faculty and student satisfaction compared to institutions using algorithmic tools. Bui et al. in 2022 investigated metaheuristic approaches to academic timetabling and found that algorithmic scheduling reduced the planning cycle from twenty-one days to three days while achieving complete hard-constraint satisfaction — no room double-bookings, no faculty conflicts, no student section overlaps. That is an eighty-six percent reduction in administrative time. Veenstra and Vis in 2023 documented that manual schedule conflict density averages eight to twelve percent — meaning eight to twelve percent of scheduled assignments contain a conflict requiring manual correction. Diallo et al. in 2024 demonstrated that constraint satisfaction-based systems can achieve one hundred percent hard-constraint satisfaction with seventy-eight percent soft-constraint fulfillment. These statistics do not merely justify SEN-GEN\'s proposed scheduling engine — they make it an operational necessity for an institution currently spending eighteen to twenty-two working days on a task that algorithmic tools can complete in two to four.',
  },
  {
    id: 's19', section: '04', sectionTitle: 'Review of Related Literature', type: 'content', title: 'Philippine HEI Evidence',
    notes: 'The Philippine-specific evidence further validates SEN-GEN\'s approach. Leite in 2025 synthesized usability data from eight academic management system deployments in Southeast Asian higher education institutions and established a critical meta-finding: systems that achieved an overall ISO 25010 weighted mean of 4.00 or above during initial user acceptance testing demonstrated a seventy-eight percent probability of continued institutional use beyond the first academic year without requiring major redesign. This finding elevates our 4.00 target from a mere quality threshold to a predictor of long-term institutional sustainability. Gkrimpizi et al. in 2024 specifically identified that small-to-medium higher education institutions are most severely impacted by the absence of integrated digital enlistment tools — precisely the context of STI Alaminos. Mansoor et al. in 2022 identified automated data import as among the highest-impact enrollment features for administrative time savings, validating our proposed ETL pipeline. Martinez and Chen in 2023 found that eighty-four percent of systems combining real-time slot availability, automated notifications, and twenty-four-seven access score above 4.0 on usability instruments — three features that are central to SEN-GEN\'s proposed student portal. And Leite in 2025 further documented that administrators use semester-filtered dashboard views three-point-four times more frequently than aggregate views — directly validating SEN-GEN\'s proposed semester-aware dashboard design.',
  },
  {
    id: 's20', section: '04', sectionTitle: 'Review of Related Literature', type: 'content', title: 'CSP & Scheduling Engine',
    notes: 'The academic scheduling problem — simultaneously assigning students, faculty, rooms, and time slots while satisfying multiple hard and soft constraints — is classified in computer science literature as NP-hard. This means there is no known polynomial-time algorithm that guarantees an optimal solution for all possible inputs. Constraint Satisfaction Problem solving, or CSP, is the established approach for NP-hard combinatorial optimization problems of this kind. Formally, a CSP is defined as a tuple of three elements: X — a finite set of variables representing the class sections to be scheduled; D — the domains, meaning the valid assignment values, in our case valid time slot, room, and faculty combinations; and C — the constraints, the rules that any solution must satisfy. Hard constraints are non-negotiable and will include: no room double-bookings, no faculty assigned to two simultaneous sections, room capacity must meet or exceed section enrollment, faculty load must not exceed STI Policy limits, and faculty must be qualified for their assigned subject. Soft constraints will be optimized where possible: faculty time preferences, minimized idle gaps, equitable load distribution. Bashab et al. in 2023 demonstrated that constraint-based algorithmic approaches achieve conflict-free schedule generation within practical timeframes for institutions at STI Alaminos\'s scale. Diallo et al. in 2024 reported one hundred percent hard-constraint satisfaction with seventy-eight percent soft-constraint fulfillment. Bui et al. in 2022 reduced the scheduling cycle from twenty-one days to three. These results directly validate SEN-GEN\'s proposed CSP engine architecture.',
  },
  {
    id: 's21', section: '04', sectionTitle: 'Review of Related Literature', type: 'content', title: 'ETL, RBAC, Dashboard & Notifications',
    notes: 'Beyond the scheduling engine, the literature validates each of SEN-GEN\'s other five proposed modules. For the ETL pipeline — Extract, Transform, Load — Mansoor et al. in 2022 documented that automated XLSX import is among the highest-impact enrollment features for administrative efficiency, directly reducing data entry errors and accelerating pre-enlistment authorization. For Role-Based Access Control, Liu et al. in 2017 examined RBAC architectures in educational administration systems and demonstrated that a tiered role structure — distinguishing student, faculty, administrative, and supervisory access levels — is operationally sound and corresponds directly to SEN-GEN\'s proposed six-role hierarchy. Kim and Park in 2022 further confirmed that RBAC significantly reduces unauthorized access risks in institutional information systems. For the semester-aware dashboard, Leite in 2025 documented that administrators use semester-filtered views three-point-four times more than aggregate historical views, and that the most valued features are enrollment count by section, room utilization percentage, and faculty load distribution — all of which are planned for SEN-GEN\'s dashboard. For automated notifications, Martinez and Chen in 2023 found that platforms incorporating five or more automated notification events achieve student-reported satisfaction scores forty-one percent higher than platforms without. SEN-GEN will trigger six notification events across the enrollment lifecycle. And for the student enlistment portal, Bellio et al. in 2022 established that pre-publication of complete, constraint-verified schedules substantially reduces manual administrative transaction volume during peak enlistment periods.',
  },
  {
    id: 's22', section: '04', sectionTitle: 'Review of Related Literature', type: 'content', title: 'ISO 25010 Benchmarks',
    notes: 'The literature provides a concrete empirical range for interpreting SEN-GEN\'s planned usability evaluation results. Bellio et al. in 2022 evaluated a constraint satisfaction-based scheduling system at a European university and reported ISO 25010 weighted mean scores of 4.52 for faculty — Excellent — and 4.45 for administrative staff — Very Good. Gozali et al. in 2022 evaluated a genetic algorithm scheduling system and reported 4.28 for faculty and 4.11 for administrative staff — both Very Good. Diallo et al. in 2024 evaluated a CSP optimization system — the most directly comparable to SEN-GEN — and reported 4.44 across all user groups. Kim and Park in 2022 reported 4.30 or above for administrative users of an RBAC-based institutional system. The overall benchmark range across all four systems is 4.11 to 4.55. SEN-GEN will target at least 4.00 — deliberately conservative, well below the floor of every comparable system in the literature. This positioning is intentional: it ensures the target is achievable while remaining meaningful. Leite in 2025 provides the capstone justification: systems scoring 4.00 or above show a seventy-eight percent probability of continued institutional adoption beyond the first academic year — directly linking our evaluation target to the long-term sustainability of SEN-GEN at STI Alaminos.',
  },
  {
    id: 's23', section: '04', sectionTitle: 'Review of Related Literature', type: 'content', title: 'Literature Synthesis & Gap',
    notes: 'The totality of the over thirty sources reviewed in this chapter collectively establishes three things. First, the operational costs of manual enrollment and scheduling are real, quantifiable, and directly applicable to STI Alaminos. Chen et al., Bashab et al., and Awad et al. provide the numbers. Second, every feature of the proposed SEN-GEN is technically grounded in proven computational approaches and addresses a specific documented operational need. Diallo et al. validates the scheduling engine approach, Mansoor et al. validates the ETL pipeline design, Martinez and Chen validate the notification strategy, Leite validates the dashboard design, Liu et al. and Kim and Park validate the RBAC architecture, and Bellio et al. and Gozali et al. validate the enlistment portal design principles. Third, the ISO 25010 framework provides both a validated evaluation methodology and an empirically grounded performance benchmark for the planned evaluation. There is one research gap that SEN-GEN directly addresses: while numerous studies have proposed scheduling algorithms for large-scale universities, and while ADMU, UP, DLSU, FEU, and UST have operated mature enlistment platforms for decades, very few studies have proposed and evaluated a purpose-built, fully integrated enlistment and scheduling system specifically designed for small-to-medium Philippine private technical-vocational institutions — where commercial enterprise platforms are neither financially accessible nor operationally suitable. SEN-GEN is proposed to fill this gap.',
  },

  // ── SECTION 05 ──────────────────────────────────────────────
  {
    id: 's24', section: '05', sectionTitle: 'Methodology', type: 'divider', title: 'Methodology',
    notes: 'We now move to Section Five: Methodology. This section covers the research design — Descriptive-Developmental — the Software Development Life Cycle — Agile Feature-Driven Development — the sources of data that will be used to build and validate SEN-GEN, the analytical tools, and the respondent sampling strategy. Each methodological choice is deliberate and anchored in academic literature. I will walk the panel through each component and the specific rationale behind it.',
  },
  {
    id: 's25', section: '05', sectionTitle: 'Methodology', type: 'content', title: 'Research Design',
    notes: 'This study employs a descriptive-developmental research design — a methodological approach that integrates the systematic description of phenomena with the structured development of a technological product. The descriptive dimension, as defined by McCombes in 2023, aims to accurately and systematically describe a population, situation, or phenomenon without manipulating variables or testing hypotheses. Applied to this study, the descriptive dimension has enabled the researcher to document and analyze the current enrollment and scheduling procedures at STI Alaminos through structured interviews with all five stakeholder groups, non-participatory observation of live workflows, and document analysis of paper forms, spreadsheets, and faculty load records. This produced the empirical operational baseline that will directly drive SEN-GEN\'s requirements. The developmental dimension, as defined by Siedlecki in 2020, is a systematic and iterative process of designing, developing, and refining a program or product over time, with the goal of improving its responsiveness to evolving technology and user demands. Wang and Hannafin in 2005 further characterize developmental research in systems design as involving cycles of prototyping, testing, and refinement grounded in both theoretical frameworks and practical stakeholder input. In this study, the developmental design will be operationalized through Agile Feature-Driven Development, which will structure SEN-GEN\'s construction into five iterative phases culminating in a fully tested and institutionally evaluated system.',
  },
  {
    id: 's26', section: '05', sectionTitle: 'Methodology', type: 'content', title: 'Agile Feature-Driven Development',
    notes: 'The Software Development Life Cycle for SEN-GEN is Agile Feature-Driven Development — FDD. FDD is proposed over Scrum, Kanban, or Waterfall for three reasons specific to the structure of this study. First, SEN-GEN has six clearly bounded functional modules — the ETL pipeline, the CSP Scheduling Engine, the Student Enrollment Portal, the Dashboard, the Notification System, and RBAC — which map naturally to FDD\'s feature-centric organization. Each module has its own requirements, design artifacts, and validation criteria, and FDD treats each as an independent deliverable. Second, unlike Scrum, FDD allows each feature to be independently designed, built, and validated before integration, reducing the risk of cascading failures between modules. Third, FDD\'s explicit feature-centric planning maps directly to the stakeholder-driven requirements established in the Descriptive phase. Palmer and Felsing in 2002 define FDD as a model-driven, short-iteration process that produces working software in every iteration. This is exactly the approach needed when six interdependent modules must be individually validated with actual STI Alaminos stakeholders before final system acceptance. The FDD process has five phases: three sequential phases executed once at the beginning of the project, and two iterative phases repeated for each of the six features.',
  },
  {
    id: 's26b', section: '05', sectionTitle: 'Methodology', type: 'content', title: 'Agile FDD — Process Diagram',
    notes: 'This diagram illustrates the five phases of Feature-Driven Development as planned for SEN-GEN. The three sequential phases on the left will be executed once at the beginning of the project. Phase One — Develop Overall Model — will establish the system architecture and data model, building on the domain knowledge already gathered through stakeholder interviews. The expected output is a ten-entity ERD and a three-tier architecture blueprint. Phase Two — Build Feature List — will formally identify and group all system features into three feature sets: Enrollment Management, Scheduling Management, and Administrative Management. Phase Three — Plan by Feature — will sequence development based on technical dependencies, placing database schema, API scaffold, and JWT-RBAC infrastructure first, since all six modules will depend on them. The two iterative phases on the right will form a cycle repeated independently for each of the six features. Phase Four — Design by Feature — will produce detailed design artifacts: ERD refinements, REST API specifications, CSP pseudocode, React component hierarchies, and as-is versus to-be process flowcharts. Phase Five — Build by Feature — will implement each feature following those design artifacts, with unit tests for business logic, integration tests for API-to-database interactions, and User Acceptance Testing sessions with actual STI Alaminos stakeholders. After each feature cycle, the feedback and review loop will inform any necessary adjustments before the next feature begins.',
  },
  {
    id: 's27', section: '05', sectionTitle: 'Methodology', type: 'content', title: 'FDD Phases 1–3',
    notes: 'Let me detail what each of the three sequential phases entails for SEN-GEN. Phase One — Develop Overall Model — builds on the stakeholder interviews and document analysis already conducted during the Descriptive phase. The expected outputs are a ten-entity Entity-Relationship Diagram capturing all core data relationships and a Three-Tier Architecture Blueprint defining React JS as the client layer, ASP.NET Core Web API plus Entity Framework Core as the application layer, and SQL Server as the data layer, hosted on IIS. Phase Two — Build Feature List — will formalize the six functional modules into three feature sets. Feature Set One covers Enrollment Management: ETL Import, Digital Document Requirements Checklist, and Student Portal. Feature Set Two covers Scheduling Management: CSP Engine, Grid Schedule Views, and Faculty Loading Report. Feature Set Three covers Administrative Management: RBAC, Dashboard Analytics, Automated Notifications, and Audit Logs. Phase Three — Plan by Feature — will sequence development by technical dependency. Database schema, API scaffold, and JWT-RBAC middleware will be built first, as all six modules depend on them. The CSP Engine will follow as the core business logic. The Student Portal will come third, depending on both ETL and scheduling. Dashboard, Notifications, and Reports will come last, depending on all prior modules.',
  },
  {
    id: 's28', section: '05', sectionTitle: 'Methodology', type: 'content', title: 'FDD Phases 4–5',
    notes: 'The iterative portion of FDD — Phases Four and Five — will be repeated independently for each of the six SEN-GEN modules. Phase Four — Design by Feature — for each feature, the researcher will produce five categories of design artifacts: detailed ERD refinements specific to the feature\'s data requirements; a complete REST API specification documenting all endpoints, request and response schemas, and HTTP status codes; CSP pseudocode and algorithm flow for the scheduling engine; React component hierarchy diagrams showing how each interface component is structured; and as-is versus to-be process flowcharts demonstrating the specific workflow transformation SEN-GEN will achieve. All design artifacts will be reviewed by STI Alaminos stakeholders before implementation begins — this validation step ensures SEN-GEN\'s design reflects actual institutional requirements, not assumed ones. Phase Five — Build by Feature — each feature will be implemented following those design artifacts. Unit tests will be written for all business logic — constraint checks, ETL validation rules, load compliance verification. Integration tests will verify API-to-database interactions under concurrent load conditions. User Acceptance Testing sessions will be conducted with actual STI Alaminos stakeholders in their assigned roles. The ISO 25010 questionnaire will be administered after UAT completion. Weighted mean analysis will then be computed per dimension and per respondent group. This iterative cycle will be completed for all six modules before final system acceptance.',
  },
  {
    id: 's29', section: '05', sectionTitle: 'Methodology', type: 'content', title: 'Data Collection',
    notes: 'The data for this study is collected from three source categories. Primary sources provide the operational baseline for SEN-GEN\'s requirements. These are structured interviews conducted with all five stakeholder groups — the Registrar, the Academic Head, the Admission Officer, Faculty Members, and Students — using semi-structured interview guides developed from the research objectives. Non-participatory observation of live enrollment and scheduling processes was also conducted to capture procedural realities that structured interviews sometimes miss — for instance, the informal coordination patterns and the specific points in the workflow where manual errors most frequently occur. Secondary sources provide institutional documentation of existing processes: paper-based SIS enrollment forms, faculty load spreadsheets, manual class scheduling files, and room assignment records from STI Alaminos. These documents were analyzed to understand the specific data structures and constraints that SEN-GEN must accommodate. Tertiary sources provide the academic and technical foundation: peer-reviewed journals, institutional publications from leading Philippine HEIs, ISO standards documentation, and technical documentation for the chosen technology stack. Together, these three source categories ensure that SEN-GEN will be grounded in institutional reality, technically sound, and academically justified.',
  },
  {
    id: 's30', section: '05', sectionTitle: 'Methodology', type: 'content', title: 'Tools for Data Analysis',
    notes: 'Six analytical tools will be used in this study, each serving a distinct analytical purpose. Use Case Diagrams will define the functional boundaries for each of the six user roles — mapping exactly what each role will be able to perform within SEN-GEN, ensuring no functional boundary gaps or overlaps, and providing a stakeholder-validated requirements reference. Flowcharts will document as-is manual workflows versus to-be SEN-GEN workflows for both enrollment and scheduling, visually demonstrating the specific transformations the proposed system aims to achieve. The Entity-Relationship Diagram captures all ten system entities, their attributes, cardinalities, and relationships — the foundational data model that will drive every SQL Server schema decision. The Database Schema is the physical implementation to be derived from the ERD: tables, columns, data types, primary keys, foreign keys, and referential integrity constraints enforced at the database level to prevent orphaned records and data inconsistencies. For usability evaluation, the Likert Scale and Weighted Mean are the primary quantitative instruments. A five-point scale — five being Strongly Agree, one being Strongly Disagree — will be used with interpretation thresholds: 4.50 to 5.00 is Excellent, 3.50 to 4.49 is Very Good, 2.50 to 3.49 is Good, 1.50 to 2.49 is Fair, and 1.00 to 1.49 is Poor. Cronbach\'s alpha of at least 0.70 is required for instrument reliability before full administration.',
  },
  {
    id: 's31', section: '05', sectionTitle: 'Methodology', type: 'content', title: 'Respondents & Sampling',
    notes: 'The evaluation of SEN-GEN will use Purposive Sampling, as defined by Bisht in 2023 — the deliberate selection of participants based on their direct relevance to the research objectives. Only users who will actually interact with SEN-GEN in their designated roles during User Acceptance Testing will be included. This is the appropriate sampling strategy for developmental research because the goal is not statistical generalizability to a broad population, but rather a valid assessment of usability within the specific institutional context of STI Alaminos. The planned respondent group consists of forty-five participants distributed across three groups: thirty students from IT and allied programs who will use the student enrollment portal during UAT; ten faculty members who will access SEN-GEN\'s schedule views, load summaries, and notification features; and five administrative staff representing the Registrar, Academic Head, Admission Officer, and School Admin roles. The instrument validation process will follow a rigorous sequential protocol: three IT expert validators will assess questionnaire items for content validity; items will be revised based on expert feedback; a pilot test will be administered to five participants; Cronbach\'s alpha will be computed to verify internal consistency at or above 0.70; and only after this threshold is confirmed will the full instrument be administered to all forty-five respondents. Weighted mean analysis will then be computed per ISO 25010 dimension and per respondent group to enable cross-role comparisons of usability perceptions.',
  },

  // ── SECTION 06 ──────────────────────────────────────────────
  {
    id: 's32', section: '06', sectionTitle: 'System Features & Architecture', type: 'divider', title: 'System Features & Architecture',
    notes: 'We now move to Section Six: System Features and Architecture. This is the technical heart of the presentation. I will describe SEN-GEN\'s proposed three-tier architecture, the technology stack and the rationale for each technology choice, and all six functional modules. For each module, I will explain the specific operational problem it is designed to address, how it will be technically implemented, and the literature that validates the approach. Every architectural decision in the proposed SEN-GEN is traceable to a stakeholder requirement identified in the Descriptive phase and validated by the literature reviewed in Section Four.',
  },
  {
    id: 's33', section: '06', sectionTitle: 'System Features & Architecture', type: 'content', title: 'Three-Tier Architecture',
    notes: 'SEN-GEN is proposed on a three-tier architecture that cleanly separates presentation, business logic, and data concerns. Tier One is the Client Layer, to be implemented in React JS. This tier will provide six distinct role-differentiated user interfaces — one for each of the six user roles. Role-differentiated UIs are a usability best practice that reduces cognitive load by ensuring each user sees only the functions and data relevant to their role. Martinez and Chen in 2023 documented that the gap between student and administrative staff usability ratings narrows significantly in systems with role-differentiated interfaces compared to uniform interfaces — directly validating this design choice. React\'s virtual DOM architecture will ensure performant rendering during peak enlistment when multiple students are simultaneously submitting slot requests. Tier Two is the Application Layer, to be implemented in ASP.NET Core Web API with Entity Framework Core, hosted on IIS. This tier will house all business logic: the CSP Generative Scheduling Engine, Role-Based Access Control with JWT middleware, the ETL pipeline, automated email notifications, slot request and approval workflows, and all business rule validation. Tier Three is the Data Layer, to be implemented in Microsoft SQL Server. Referential integrity constraints at the database level will prevent orphaned records. Transactional consistency will ensure slot capacity is enforced even under concurrent requests. Separation of concerns across all three tiers directly supports the Maintainability and Portability quality dimensions of ISO 25010.',
  },
  {
    id: 's34', section: '06', sectionTitle: 'System Features & Architecture', type: 'content', title: 'Technology Stack',
    notes: 'Each technology in SEN-GEN\'s proposed stack is selected for specific, defensible reasons. React JS is proposed for its component-based architecture, which will directly enable the six role-differentiated interfaces through reusable, role-aware components. React\'s virtual DOM will ensure performant rendering during peak enlistment load — when multiple students are simultaneously browsing sections and submitting requests. ASP.NET Core Web API is proposed for its built-in dependency injection, JWT middleware support, cross-platform compatibility, and high maintainability rating in ISO 25010 benchmarks, as documented by Kim and Park in 2022. Entity Framework Core will provide code-first database migrations that ensure schema consistency across development and production environments. For the CSP engine specifically, raw optimized SQL queries will be used instead of ORM abstractions to avoid computational overhead during constraint evaluation — a deliberate performance design decision for the most computationally intensive component. Microsoft SQL Server will provide referential integrity constraints and transactional consistency to enforce slot capacity even under concurrent load. IIS will provide HTTP routing and SSL/TLS encryption, ensuring that all data in transit is protected in compliance with Republic Act 10173, the Data Privacy Act of 2012. The ISO/IEC 25010:2023 standard explicitly identifies portability as a core quality characteristic; React JS and ASP.NET Core are cross-platform by design, directly satisfying this dimension.',
  },
  {
    id: 's35', section: '06', sectionTitle: 'System Features & Architecture', type: 'content', title: 'Feature 1: ETL Import',
    notes: 'The first proposed feature is the ETL — Extract, Transform, Load — pre-enrollment import pipeline. This feature is designed to directly address the absence of a systematic pre-enlistment authorization mechanism at STI Alaminos. Currently, the Registrar has no digital mechanism to authorize which students are eligible to enlist for a given semester. The proposed workflow is as follows. The Registrar will upload an XLSX file containing the authorized pre-enrollment student list for the current semester. In the Extract phase, a server-side parser will read all rows into memory. In the Transform phase, field completeness will be validated — student ID, name, program, year level — and malformed or duplicate rows will be flagged and returned to the Registrar with specific error details for correction. Valid rows will be mapped to curriculum records and pre-enrollment tokens will be generated per semester, per student. In the Load phase, validated records will be inserted into SQL Server, activating each student\'s online enlistment eligibility for that specific enrollment period. This is designed to replace the manual per-student eligibility verification that currently burdens both the Registrar and the Academic Head every semester. Mansoor et al. in 2022 identifies automated XLSX import as among the highest-impact enrollment features for reducing administrative time and data entry errors — directly validating this proposed approach.',
  },
  {
    id: 's36', section: '06', sectionTitle: 'System Features & Architecture', type: 'content', title: 'Feature 2: Scheduling Engine',
    notes: 'The CSP-Based Generative Scheduling Engine is the algorithmic core of SEN-GEN and the most technically complex component of the proposed system. The Academic Head will initiate schedule generation for a semester. The engine will execute a five-step process. First, it defines the variables — each class section that needs to be scheduled for the semester. Second, it defines the domains — all valid combinations of time slot, room, and faculty for each section. Third, it evaluates constraints. Hard constraints will be checked first: no room double-booking, no faculty assigned to two simultaneous sections, room capacity must meet or exceed section enrollment, faculty load must not exceed STI Policy limits, and faculty must be qualified for their assigned subject. Soft constraints will then be optimized: faculty time preferences, minimized idle gaps between classes, equitable load distribution across all faculty. Fourth, constraint propagation will reduce the search space before backtracking begins, significantly improving engine efficiency. Fifth, backtracking will find the first fully satisfying assignment. Manual override with real-time conflict detection will be available for the Academic Head, accommodating the approximately twelve percent of assignments that Zhou in 2025 documented as requiring coordinator intervention in real-world deployments. This override capability is not optional — it is essential for realistic institutional adoption. Press the View CSP Engine Detail button to see the full technical breakdown.',
  },
  // ── HIDDEN: CSP Detail slide — press button on s36 to open ──
  {
    id: 's36b', section: '06', sectionTitle: 'System Features & Architecture', type: 'content', title: 'CSP Engine — Technical Detail', hidden: true,
    notes: 'Formally, the proposed CSP scheduling engine is defined as a tuple — X, D, C — where X is a finite set of variables representing the class sections to be scheduled; D is the set of domains, the valid time slot, room, and faculty combinations for each variable; and C is the set of constraints that any solution must satisfy. SEN-GEN will implement backtracking search enhanced with three key optimizations that together transform a computationally intractable brute-force search into a practically efficient scheduling process. First, Forward Checking and Arc Consistency through the AC-3 algorithm. When a value is assigned to a variable, AC-3 will propagate that assignment through the constraint graph and remove inconsistent values from neighboring variable domains before any further assignments are attempted. This dramatically reduces the search space. Second, the Minimum Remaining Values heuristic — MRV. The engine will select the unassigned variable with the fewest remaining legal domain values first. This is the "fail-first" strategy: by tackling the most constrained scheduling decision early, the engine discovers dead ends sooner and backtracks less overall. Third, the Least Constraining Value heuristic — LCV. When selecting a domain value for a variable, the engine will prefer the value that eliminates the fewest options from neighboring variables, maximizing flexibility for subsequent scheduling decisions. Diallo et al. in 2024 achieved one hundred percent hard-constraint satisfaction with seventy-eight percent soft-constraint fulfillment using this approach. Bui et al. in 2022 reduced scheduling time from twenty-one days to three. Zhou in 2025 established that approximately twelve percent of assignments require manual override in production deployments — which is precisely why SEN-GEN\'s override feature is a planned core component, not an afterthought.',
  },
  {
    id: 's37', section: '06', sectionTitle: 'System Features & Architecture', type: 'content', title: 'Feature 3: Student Enrollment Portal',
    notes: 'The proposed Student Enrollment Portal will digitize the enlistment step of the four-step enrollment process — the step currently requiring a mandatory physical registrar visit. The pre-condition for portal access will be ETL authorization: a student must have been included in the Registrar\'s XLSX import for the current semester. This ensures only eligible students can access the portal without any manual eligibility check by registrar staff. Once authorized, the student will have twenty-four-seven access from any device to browse all published class sections. For each section, the portal will display real-time slot availability, room assignment, time, faculty name, and remaining capacity — all information that currently requires a physical registrar visit to obtain. The student will submit slot requests for their desired sections, which will enter a Registrar approval queue. Upon approval, the student will receive an automated email confirmation. Slot capacity — a maximum of forty students per section — will be enforced simultaneously at both the application and database levels, preventing race conditions during simultaneous requests from multiple students. This dual-level enforcement is a critical design decision: application-level checks alone can be bypassed under concurrent load; database-level constraints provide the final guarantee. Martinez and Chen in 2023 documented that eighty-four percent of systems combining real-time slots, automated notifications, and twenty-four-seven access score above 4.0 on usability instruments — directly validating this proposed portal design.',
  },
  {
    id: 's38', section: '06', sectionTitle: 'System Features & Architecture', type: 'content', title: 'Feature 4: Dashboard',
    notes: 'The proposed semester-aware administrative dashboard will provide real-time institutional analytics to the School Admin and Academic Head — the two roles currently operating without any real-time operational visibility. The defining design principle is semester-awareness: every metric in the dashboard will automatically filter to the active semester. Leite in 2025 documented that administrators use semester-filtered views three-point-four times more frequently than aggregate historical views, and that the most valued dashboard features are enrollment count by section, room utilization percentage, faculty load distribution, and pre-enrollment application volume — all of which are planned for SEN-GEN\'s dashboard. Live enrollment statistics will be displayed per subject, section, and program. Room utilization will be computed automatically as a percentage per semester, with peak usage periods identified — eliminating the manual tallying currently required of the Registrar. Faculty load distribution will be visualized as a comparison of assigned units versus STI Policy limits, with automatic flags when any faculty member approaches or exceeds the policy maximum. This is designed to eliminate the informal, spreadsheet-based load compliance monitoring that currently leaves imbalances undetected. All reports will be exportable for STI institutional documentation. A comprehensive audit trail will record all administrative actions for accountability and transparency.',
  },
  {
    id: 's39', section: '06', sectionTitle: 'System Features & Architecture', type: 'content', title: 'Features 5 & 6: Notifications + RBAC',
    notes: 'Feature Five is the proposed Automated Email Notification System. SEN-GEN will trigger automated notifications at six enrollment lifecycle events: when enrollment requirements are submitted and verified, when pre-enrollment is confirmed, when a slot request is received, when a slot request is approved or declined, when a schedule is published, and when a faculty assignment is confirmed. Currently, students learn about their enrollment status through word of mouth or by making repeat visits to the registrar\'s office. Martinez and Chen in 2023 found that platforms with five or more automated notification events achieve student satisfaction scores forty-one percent higher than platforms without. The two notification categories most strongly associated with satisfaction improvement are slot approval confirmations and schedule publication alerts — both of which are included in SEN-GEN\'s proposed notification design. Feature Six is the proposed Role-Based Access Control system. Six distinct roles — School Admin, Academic Head, Registrar, Admission Officer, Faculty Member, and Student — will each have a role-differentiated interface and strictly enforced permission boundaries. Every API request will be validated by JWT middleware before any data is returned or modified. IIS and SSL/TLS will encrypt all data in transit. Liu et al. in 2017 confirmed that a tiered role structure strengthens both system security and operational clarity under concurrent multi-user access — both critical requirements during peak enrollment. Full compliance with Republic Act 10173, the Data Privacy Act of 2012, will be enforced at both the application and transport layers.',
  },
  {
    id: 's39b', section: '06', sectionTitle: 'System Features & Architecture', type: 'content', title: 'Additional System Features',
    notes: 'Beyond the six core modules, SEN-GEN is designed to include several additional features that directly address the specific operational gaps documented in the Descriptive phase. The Digital Enrollment Requirements Checklist will enable the Admission Officer to manage document submissions — Form 137, birth certificate, good moral certificate — through a structured digital checklist, eliminating the paper-based manual verification that currently creates incomplete records and late discovery of missing pertinent papers. The self-service Student Registration module will digitize the SIS form with enforced terms and conditions acknowledgment, proper name capitalization, and field validation — addressing all the specific deficiencies of the apply.sti.edu platform that led to its non-use. Grid Schedule Views with PDF and XLSX export will provide Faculty View, Classroom View, and Class Section View — exportable for offline review and STI compliance documentation. The Automated Room Utilization Report will compute room usage percentage per semester, identify peak periods, and generate downloadable reports, replacing the manual tallying currently required. Automated Schedule Change Notifications will send instant email alerts when any schedule revision occurs, eliminating word-of-mouth propagation of changes. And the Automated Faculty Loading Report will generate a consolidated workload report each semester with STI Policy compliance flags for every faculty member — providing the Academic Head with a documented, exportable record that the institution currently has no mechanism to produce. Each of these proposed features traces directly to a documented gap identified in the Descriptive phase.',
  },

  // ── SECTION 07 ──────────────────────────────────────────────
  {
    id: 's40', section: '07', sectionTitle: 'Evaluation Framework', type: 'divider', title: 'Evaluation Framework',
    notes: 'We now move to Section Seven: the Evaluation Framework. This section presents the ISO/IEC 25010:2023 quality model that will be used to assess SEN-GEN, the six quality dimensions selected for evaluation, the questionnaire instrument and its planned validation process, and the empirically grounded benchmark range against which SEN-GEN\'s results will be interpreted. Adopting ISO 25010 ensures that SEN-GEN will be assessed against an internationally recognized and validated quality model rather than an ad hoc rubric, which strengthens the credibility of the evaluation results for STI institutional quality audits, academic publication, and future institutional decision-making regarding the system.',
  },
  {
    id: 's41', section: '07', sectionTitle: 'Evaluation Framework', type: 'content', title: 'ISO 25010 — Six Dimensions',
    notes: 'The ISO/IEC 25010:2023 standard defines eight quality characteristics. For SEN-GEN, six of these dimensions will be evaluated using end-user survey instruments — the approach validated by Suryadi and Sulistiyani in 2022 as most amenable to respondent-based assessment of academic information systems. The first dimension is Functional Suitability: will SEN-GEN accurately perform all its stated functions? Rojas in 2025 documented that functional suitability is the dimension most consistently prioritized by end-users of academic information systems — particularly by faculty and administrative staff who depend on generated schedules and enrollment confirmations being correct. The second is Performance Efficiency: will the system respond quickly under concurrent peak load? Critical during enlistment windows when multiple students submit requests simultaneously. The third is Usability: will the system be intuitive for all six roles without extensive training? The proposed role-differentiated interfaces are designed to directly address this. The fourth is Reliability: will the system be stable under peak load and able to recover gracefully from errors? Downtime during enlistment would prevent students from meeting registration deadlines. The fifth is Maintainability: will the system be modifiable as STI policies evolve? The modular FDD architecture is specifically designed to support this over time. The sixth is Portability: will the system work consistently across devices, browsers, and deployment environments? React JS and ASP.NET Core are cross-platform by design, and ISO/IEC 25010:2023 explicitly identifies this technology profile as associated with high portability ratings.',
  },
  {
    id: 's42', section: '07', sectionTitle: 'Evaluation Framework', type: 'content', title: 'Evaluation Instrument',
    notes: 'The evaluation instrument will be a five-point Likert questionnaire adapted from ISO/IEC 25010:2023 and validated following the approach of Suryadi and Sulistiyani in 2022. Each item will be phrased as a statement that respondents rate from one — Strongly Disagree — to five — Strongly Agree. Representative items include: "The system accurately performs enrollment and scheduling functions" for Functional Suitability; "The system responds quickly even during peak enrollment periods" for Performance Efficiency; "I can navigate the system without extensive training" for Usability; "The system operates consistently without unexpected errors" for Reliability; "The system can be updated as institutional policies change" for Maintainability; and "The system works consistently across different devices and browsers" for Portability. The instrument will be validated through a five-step sequential process. Expert panel review: three IT experts will assess all questionnaire items for content validity, and items will be revised based on their feedback. Pilot test: the revised instrument will be administered to five participants. Cronbach\'s alpha computation: internal consistency will be verified at or above the 0.70 threshold before full administration. Full administration: the validated instrument will be administered to all forty-five respondents after UAT. Weighted mean computation: results will be analyzed per dimension and per respondent group, interpreted using the scale — 4.50 to 5.00 Excellent, 3.50 to 4.49 Very Good, 2.50 to 3.49 Good, 1.50 to 2.49 Fair, 1.00 to 1.49 Poor.',
  },
  {
    id: 's43', section: '07', sectionTitle: 'Evaluation Framework', type: 'content', title: 'Usability Benchmarks',
    notes: 'The target for SEN-GEN\'s ISO 25010 evaluation is a weighted mean of at least 4.00 across all six quality dimensions. This target is not arbitrarily chosen — it is empirically grounded in four comparable systems documented in the literature. Bellio et al. in 2022 reported 4.52 for faculty and 4.45 for administrative staff at a European university using a constraint satisfaction-based scheduling system. Gozali et al. in 2022 reported 4.28 for faculty and 4.11 for administrative staff for a genetic algorithm scheduling system. Diallo et al. in 2024 — the most directly comparable study, using CSP — reported 4.44 across all user groups including academic coordinators, faculty, and students. Kim and Park in 2022 reported 4.30 or above for administrative users of an RBAC-based institutional system. The benchmark range across all four comparable systems is 4.11 to 4.55. SEN-GEN will target at least 4.00 — deliberately conservative, well below the floor of every comparable system in the literature. This positioning is intentional: it ensures the target is both meaningful and achievable, so that achieving it constitutes a defensible demonstration of institutional-level usability. Leite in 2025 provides the capstone justification for why 4.00 matters: systems scoring 4.00 or above during initial user acceptance testing show a seventy-eight percent probability of continued institutional adoption beyond the first academic year — directly linking our evaluation target to the long-term sustainability of SEN-GEN at STI Alaminos.',
  },

  // ── SECTION 08 ──────────────────────────────────────────────
  {
    id: 's44', section: '08', sectionTitle: 'Significance & Summary', type: 'divider', title: 'Significance & Summary',
    notes: 'We now move to the final section: Significance and Summary. SEN-GEN is not merely a technical solution to an operational problem — it is aligned with national legislation, international development goals, and STI\'s own institutional direction toward technology-driven education. In this section, I will present the regulatory and policy alignment of SEN-GEN, the direct and indirect beneficiaries across all stakeholder groups, and a concise research summary that ties all eight sections together.',
  },
  {
    id: 's45', section: '08', sectionTitle: 'Significance & Summary', type: 'content', title: 'Regulatory & Policy Alignment',
    notes: 'SEN-GEN\'s proposed development is aligned with four regulatory and policy frameworks. First, STI\'s own institutional direction. Through digital platforms such as the One STI Student Portal and other technology-enabled academic services, STI emphasizes technology-driven education and efficient service delivery. SEN-GEN is designed to support this institutional direction by automating enrollment, faculty loading, room utilization analysis, and schedule generation — extending STI\'s technology commitment to the STI Alaminos campus level. Second, Republic Act 10844 — the Department of Information and Communications Technology Act of 2015 — mandates the use of ICT to improve institutional service delivery. SEN-GEN is proposed to directly digitalize the full STI Alaminos enrollment and scheduling process, fulfilling this mandate. Third, Republic Act 10173 — the Data Privacy Act of 2012 — governs the secure handling of student and faculty data within any institutional information system. SEN-GEN is designed with JWT authentication, role-based access control with strictly enforced permission boundaries, IIS-enforced SSL/TLS encryption for all data in transit, and comprehensive audit logging — ensuring full compliance with every applicable data privacy requirement. Fourth, the United Nations Sustainable Development Goals. SDG 4 — Quality Education — calls for inclusive and equitable education for all. SEN-GEN\'s proposed twenty-four-seven student portal is designed to eliminate the in-person access requirement that currently disadvantages students with geographic, economic, or time constraints. SDG 9 — Industry, Innovation and Infrastructure — advocates for resilient, reliable digital infrastructure. SEN-GEN aims to replace fragmented manual processes with a cohesive integrated platform.',
  },
  {
    id: 's46', section: '08', sectionTitle: 'Significance & Summary', type: 'content', title: 'Significance & Beneficiaries',
    notes: 'SEN-GEN is designed to benefit every stakeholder group at STI Alaminos in specific, documented ways. STI Alaminos as an institution will gain an integrated digital platform, real-time reporting capability, and data-driven planning infrastructure that directly supports STI institutional quality audit requirements and positions the campus for stronger audit performance. The School Admin will gain real-time institutional visibility through the semester-aware dashboard — replacing manually compiled, after-the-fact reports. The Registrar will gain the ETL import pipeline, digital approval queue, automated notifications, and exportable reports — drastically reducing the manual transaction volume that currently exceeds sustainable processing capacity during peak enrollment periods. The Academic Head will gain a scheduling engine that aims to eliminate the eighteen-to-twenty-two day manual scheduling cycle and a load compliance dashboard that will automatically flag policy violations — replacing manual cross-referencing. The Admission Officer will gain a digital document requirements checklist providing structured, trackable verification of every new enrollee\'s pertinent papers — eliminating paper-based verification and late discovery of incomplete submissions. Faculty Members will gain system-enforced load management, a digital schedule view, and automated notifications — replacing informal tracking and word-of-mouth communication. Students will gain twenty-four-seven online access for document submission, registration, and subject enlistment — eliminating the in-person requirement that structurally disadvantages those with work obligations, geographic distance, or transportation limitations. And Future Researchers will gain a documented, replicable reference architecture for integrated enrollment and scheduling systems for small-to-medium Philippine private HEIs.',
  },
  {
    id: 's47', section: '08', sectionTitle: 'Significance & Summary', type: 'content', title: 'Research Summary',
    notes: 'To summarize: SEN-GEN is proposed in direct response to eight documented operational gaps at STI Alaminos, following a Descriptive-Developmental research design to be executed through Agile Feature-Driven Development. The Descriptive phase — conducted through structured interviews with five stakeholder groups, non-participatory observation, and document analysis — has established that STI Alaminos currently has no integrated digital enrollment platform, no automated scheduling mechanism, and no systematic faculty load monitoring tool. The Developmental phase will produce SEN-GEN: a proposed web-based system with six functional modules — ETL pre-enrollment import, CSP Generative Scheduling Engine, Student Enrollment Portal, Semester-Aware Dashboard, Automated Email Notifications, and Role-Based Access Control — to be delivered through a three-tier architecture using React JS, ASP.NET Core Web API with Entity Framework Core, Microsoft SQL Server, and IIS. The Evaluation phase will apply ISO/IEC 25010:2023 across six quality dimensions to forty-five purposively sampled respondents, targeting a weighted mean of at least 4.00 — a conservative threshold below the floor of all comparable systems in the literature, with Leite in 2025 establishing that systems achieving this threshold show a seventy-eight percent probability of continued institutional adoption beyond the first academic year. SEN-GEN is aligned with STI\'s institutional technology direction, Republic Act 10844, Republic Act 10173, UN SDG 4, and UN SDG 9. It is not merely a technological upgrade — it is a proposed instrument of academic quality, institutional efficiency, and student-centered service delivery.',
  },
  {
    id: 's48', section: '08', sectionTitle: 'Significance & Summary', type: 'closing', title: 'Thank You',
    notes: 'Distinguished panel members, thank you for your time and attention throughout this presentation. SEN-GEN is a research proposal grounded in over thirty verified literature sources, informed by structured stakeholder interviews at STI Alaminos, and designed to address specific, documented operational realities rather than hypothetical needs. Every proposed architectural decision is traceable to a stakeholder requirement. Every feature is validated by peer-reviewed literature. Every evaluation target is empirically grounded in comparable system benchmarks. I believe SEN-GEN is both a technically sound and institutionally meaningful proposal for a well-documented problem. I am fully prepared to address the panel\'s questions on any aspect of the study — the proposed CSP algorithm and its design rationale, the FDD methodology and how it will be applied, the planned ISO 25010 evaluation design and respondent selection, the technology stack choices and their rationale, the scope and limitation boundaries and why they are drawn where they are, or the regulatory and policy alignment of the proposed system. Press E to view the interview evidence documentation from the STI Alaminos stakeholder interviews conducted during the Descriptive phase of this research.',
  },

  // ── HIDDEN SLIDES ────────────────────────────────────────────
  // Press E to open the evidence slide
  {
    id: 's_evidence', section: '08', sectionTitle: 'Significance & Summary', type: 'content', title: 'Interview Evidence', hidden: true,
    notes: 'These photographs document the structured interviews conducted with STI Alaminos stakeholders during the Descriptive phase of this research. The interviews were conducted using semi-structured interview guides developed from the research objectives to all five stakeholder groups. The Admission Officer interviews documented the specific deficiencies of the apply.sti.edu platform — the absence of terms and conditions disclosure, forced lowercase name entry, lack of input validation, and missing document requirements checklist functionality — that led the Admission Officer to revert entirely to paper-based SIS forms and manual spreadsheets. The Registrar interviews documented the manual enlistment workflow, the spreadsheet-based slot capacity management, and the scheduling coordination burden that reaches unsustainable levels during peak enrollment periods. The Academic Head interviews documented the eighteen-to-twenty-two day manual scheduling cycle, the informal faculty load management process, and the complete absence of any systematic tool for monitoring whether teaching loads remain balanced across all faculty members in accordance with STI\'s institutional loading guidelines. The Faculty Member interviews documented the informal nature of schedule communication, the absence of digital load monitoring, and the reliance on word-of-mouth for schedule change notifications. The Student interviews documented the in-person enlistment requirement, the access barriers faced by working students and those with geographic constraints, and the strong preference for a digital self-service portal. Together, these interviews constitute the primary empirical foundation from which SEN-GEN\'s proposed requirements are derived. Press Escape to return to the presentation.',
  },
]
